export default function Products(){
  return [
  {
    "id": 1,
    "title": "Artisan Sourdough Bread Kit",
    "description": "100-year-old starter culture, proofing basket, lame, banneton, and comprehensive baking guide.",
    "price": 74.99,
    "rating": 4.8,
    "reviews": 319,
    "difficulty": "Beginner",
    "category": "Sourdough",
    "tags": ["bestseller", "complete kit", "organic"],
    "inStock": true,
    "image": "/images/kits/sourdough-artisan.jpg"
  },
  {
    "id": 2,
    "title": "Complete Kombucha Brewing Kit",
    "description": "1-gallon glass jar, organic SCOBY, pH strips, temperature gauge, and recipe booklet.",
    "price": 59.99,
    "rating": 4.9,
    "reviews": 512,
    "difficulty": "Beginner",
    "category": "Kombucha",
    "tags": ["organic", "all-in-one", "new"],
    "inStock": true,
    "image": "/images/kits/kombucha-complete.jpg"
  },
  {
    "id": 3,
    "title": "German-Style Sauerkraut Fermentation Set",
    "description": "5L stoneware crock, ceramic weights, wooden tamper, and traditional recipes.",
    "price": 139.99,
    "rating": 5.0,
    "reviews": 187,
    "difficulty": "Intermediate",
    "category": "Vegetable Fermentation",
    "tags": ["premium", "handcrafted"],
    "inStock": true,
    "image": "/images/kits/sauerkraut-german.jpg"
  },
  {
    "id": 4,
    "title": "Kimchi Master Kit",
    "description": "Fermentation jar, gochugaru, gloves, masher, and video guide.",
    "price": 68.50,
    "rating": 4.7,
    "reviews": 203,
    "difficulty": "Intermediate",
    "category": "Kimchi",
    "tags": ["spicy", "authentic"],
    "inStock": true,
    "image": "/images/kits/kimchi-master.jpg"
  },
  {
    "id": 5,
    "title": "Probiotic Yogurt & Kefir Starter Pack",
    "description": "Live kefir grains, heirloom yogurt culture, jars, thermometer, and guide.",
    "price": 44.99,
    "rating": 4.6,
    "reviews": 98,
    "difficulty": "Beginner",
    "category": "Dairy Fermentation",
    "tags": ["probiotic", "reusable"],
    "inStock": true,
    "image": "/images/kits/yogurt-kefir.jpg"
  },
  {
    "id": 6,
    "title": "Wild Fermentation Explorer Bundle",
    "description": "Water kefir, ginger beer plant, jun SCOBY + brewing vessels.",
    "price": 89.99,
    "rating": 4.9,
    "reviews": 156,
    "difficulty": "Advanced",
    "category": "Mixed Fermentation",
    "tags": ["experimental", "limited"],
    "inStock": false,
    "image": "/images/kits/wild-bundle.jpg"
  },
  {
    "id": 7,
    "title": "Home Brewed Hot Sauce Kit",
    "description": "Jars, airlocks, chili seeds, pH meter, bottles, and spicy recipes.",
    "price": 54.99,
    "rating": 4.8,
    "reviews": 274,
    "difficulty": "Intermediate",
    "category": "Condiments",
    "tags": ["spicy", "DIY"],
    "inStock": true,
    "image": "/images/kits/hot-sauce.jpg"
  },
  {
    "id": 8,
    "title": "Sourdough Baker’s Deluxe Set",
    "description": "Double banneton, dough whisk, lame, proofing cloth, digital scale.",
    "price": 109.99,
    "rating": 5.0,
    "reviews": 89,
    "difficulty": "Advanced",
    "category": "Sourdough",
    "tags": ["pro tools", "precision"],
    "inStock": true,
    "image": "/images/kits/sourdough-deluxe.jpg"
  },
  {
    "id": 9,
    "title": "Jun Kombucha Starter Kit",
    "description": "Organic jun SCOBY, green tea, honey, glass jar, and brewing guide.",
    "price": 64.99,
    "rating": 4.7,
    "reviews": 132,
    "difficulty": "Beginner",
    "category": "Kombucha",
    "tags": ["honey-based", "light"],
    "inStock": true,
    "image": "/images/kits/jun-kit.jpg"
  },
  {
    "id": 10,
    "title": "Miso Making Kit",
    "description": "Koji rice, soybeans, sea salt, fermentation crock, and aging guide.",
    "price": 79.99,
    "rating": 4.9,
    "reviews": 67,
    "difficulty": "Advanced",
    "category": "Miso",
    "tags": ["umami", "long ferment"],
    "inStock": true,
    "image": "/images/kits/miso-kit.jpg"
  },
  {
    "id": 11,
    "title": "Water Kefir Starter Pack",
    "description": "Live water kefir grains, cane sugar, mineral drops, and flavor guide.",
    "price": 39.99,
    "rating": 4.8,
    "reviews": 210,
    "difficulty": "Beginner",
    "category": "Kefir",
    "tags": ["dairy-free", "probiotic"],
    "inStock": true,
    "image": "/images/kits/water-kefir.jpg"
  },
  {
    "id": 12,
    "title": "Fermented Pickle Pro Kit",
    "description": "Half-gallon jars, airlocks, weights, pickling spice, and brine chart.",
    "price": 52.99,
    "rating": 4.7,
    "reviews": 188,
    "difficulty": "Beginner",
    "category": "Vegetable Fermentation",
    "tags": ["crisp", "easy"],
    "inStock": true,
    "image": "/images/kits/pickle-pro.jpg"
  },
  {
    "id": 13,
    "title": "Kombucha Continuous Brew System",
    "description": "3-gallon porcelain vessel, spigot, SCOBY hotel, and flavor pack.",
    "price": 149.99,
    "rating": 5.0,
    "reviews": 94,
    "difficulty": "Intermediate",
    "category": "Kombucha",
    "tags": ["continuous", "large batch"],
    "inStock": true,
    "image": "/images/kits/continuous-brew.jpg"
  },
  {
    "id": 14,
    "title": "Tempeh Starter Kit",
    "description": "Tempeh spores, incubator bag, soybeans, and step-by-step guide.",
    "price": 49.99,
    "rating": 4.6,
    "reviews": 78,
    "difficulty": "Intermediate",
    "category": "Tempeh",
    "tags": ["plant protein", "vegan"],
    "inStock": true,
    "image": "/images/kits/tempeh-kit.jpg"
  },
  {
    "id": 15,
    "title": "Sourdough Maintenance Kit",
    "description": "Starter jar, feeding scale, proofing mat, and maintenance logbook.",
    "price": 34.99,
    "rating": 4.8,
    "reviews": 145,
    "difficulty": "Beginner",
    "category": "Sourdough",
    "tags": ["daily care", "gift"],
    "inStock": true,
    "image": "/images/kits/sourdough-maintenance.jpg"
  },
  {
    "id": 16,
    "title": "Fermented Hot Sauce Masterclass Kit",
    "description": "Fermentation jars, 5 chili varieties, pH meter, and online course.",
    "price": 89.99,
    "rating": 4.9,
    "reviews": 112,
    "difficulty": "Advanced",
    "category": "Condiments",
    "tags": ["course included", "spicy"],
    "inStock": true,
    "image": "/images/kits/hot-sauce-master.jpg"
  },
  {
    "id": 17,
    "title": "Kombucha Flavor Lab",
    "description": "10 fruit purees, herbs, spices, bottles, and experimental recipes.",
    "price": 42.99,
    "rating": 4.7,
    "reviews": 166,
    "difficulty": "Intermediate",
    "category": "Kombucha",
    "tags": ["creative", "flavoring"],
    "inStock": true,
    "image": "/images/kits/flavor-lab.jpg"
  },
  {
    "id": 18,
    "title": "Traditional Kvass Brewing Kit",
    "description": "Rye bread culture, beets, jar, and Eastern European recipes.",
    "price": 55.99,
    "rating": 4.8,
    "reviews": 83,
    "difficulty": "Intermediate",
    "category": "Kvass",
    "tags": ["traditional", "beet-based"],
    "inStock": true,
    "image": "/images/kits/kvass-kit.jpg"
  },
  {
    "id": 19,
    "title": "Fermentation Station Bundle",
    "description": "4 half-gallon jars, airlocks, weights, labels, and pH strips.",
    "price": 79.99,
    "rating": 4.9,
    "reviews": 201,
    "difficulty": "Beginner",
    "category": "Multi-Use",
    "tags": ["value pack", "starter"],
    "inStock": true,
    "image": "/images/kits/fermentation-station.jpg"
  },
  {
    "id": 20,
    "title": "Sourdough Pizza Kit",
    "description": "High-hydration starter, pizza peel, stone, and Neapolitan guide.",
    "price": 94.99,
    "rating": 4.8,
    "reviews": 134,
    "difficulty": "Intermediate",
    "category": "Sourdough",
    "tags": ["pizza night", "family"],
    "inStock": true,
    "image": "/images/kits/sourdough-pizza.jpg"
  },
  {
    "id": 21,
    "title": "Fermented Condiment Trio",
    "description": "Ketchup, mustard, and sriracha kits with bottles and labels.",
    "price": 59.99,
    "rating": 4.7,
    "reviews": 97,
    "difficulty": "Intermediate",
    "category": "Condiments",
    "tags": ["gift set", "DIY pantry"],
    "inStock": true,
    "image": "/images/kits/condiment-trio.jpg"
  },
  {
    "id": 22,
    "title": "Kombucha SCOBY Hotel Kit",
    "description": "Large jar, extra SCOBYs, starter tea, and long-term storage guide.",
    "price": 38.99,
    "rating": 4.6,
    "reviews": 76,
    "difficulty": "Beginner",
    "category": "Kombucha",
    "tags": ["backup", "brewer essential"],
    "inStock": true,
    "image": "/images/kits/scoby-hotel.jpg"
  },
  {
    "id": 23,
    "title": "Fermented Beverage Starter Pack",
    "description": "Ginger beer, water kefir, and jun cultures in one box.",
    "price": 69.99,
    "rating": 4.8,
    "reviews": 155,
    "difficulty": "Beginner",
    "category": "Beverages",
    "tags": ["variety", "non-alcoholic"],
    "inStock": true,
    "image": "/images/kits/beverage-pack.jpg"
  },
  {
    "id": 24,
    "title": "Sourdough Bagel Kit",
    "description": "NY-style starter, diastatic malt, lye, and shaping tools.",
    "price": 72.99,
    "rating": 4.9,
    "reviews": 103,
    "difficulty": "Advanced",
    "category": "Sourdough",
    "tags": ["authentic", "chewy"],
    "inStock": true,
    "image": "/images/kits/bagel-kit.jpg"
  },
  {
    "id": 25,
    "title": "Fermented Vegetable Medley Kit",
    "description": "Carrots, beets, cabbage, and spices for rainbow kraut.",
    "price": 48.99,
    "rating": 4.7,
    "reviews": 129,
    "difficulty": "Beginner",
    "category": "Vegetable Fermentation",
    "tags": ["colorful", "gut health"],
    "inStock": true,
    "image": "/images/kits/veg-medley.jpg"
  },
  {
    "id": 26,
    "title": "Kombucha Second Fermentation Kit",
    "description": "Flip-top bottles, fruit purees, herbs, and carbonation guide.",
    "price": 44.99,
    "rating": 4.8,
    "reviews": 181,
    "difficulty": "Intermediate",
    "category": "Kombucha",
    "tags": ["fizz", "flavor bomb"],
    "inStock": true,
    "image": "/images/kits/second-ferment.jpg"
  },
  {
    "id": 27,
    "title": "Sourdough Scoring Art Kit",
    "description": "5 lames, stencil set, proofing basket, and design guide.",
    "price": 59.99,
    "rating": 4.9,
    "reviews": 88,
    "difficulty": "Intermediate",
    "category": "Sourdough",
    "tags": ["artistic", "gift"],
    "inStock": true,
    "image": "/images/kits/scoring-art.jpg"
  },
  {
    "id": 28,
    "title": "Fermented Dairy Deluxe",
    "description": "Yogurt, kefir, cheese cultures, press, and aging mats.",
    "price": 119.99,
    "rating": 5.0,
    "reviews": 67,
    "difficulty": "Advanced",
    "category": "Dairy Fermentation",
    "tags": ["cheese making", "probiotic"],
    "inStock": true,
    "image": "/images/kits/dairy-deluxe.jpg"
  },
  {
    "id": 29,
    "title": "Kombucha pH & Testing Lab",
    "description": "Digital pH meter, test strips, thermometer, and logbook.",
    "price": 54.99,
    "rating": 4.8,
    "reviews": 143,
    "difficulty": "Intermediate",
    "category": "Kombucha",
    "tags": ["precision", "science"],
    "inStock": true,
    "image": "/images/kits/ph-lab.jpg"
  },
  {
    "id": 30,
    "title": "Fermented Hot Pepper Paste Kit",
    "description": "Gochujang-style: peppers, rice, salt, crock, and aging guide.",
    "price": 62.99,
    "rating": 4.7,
    "reviews": 95,
    "difficulty": "Advanced",
    "category": "Condiments",
    "tags": ["Korean", "umami"],
    "inStock": true,
    "image": "/images/kits/gochujang-kit.jpg"
  },
  {
    "id": 31,
    "title": "Sourdough Starter Revival Kit",
    "description": "Dehydrated starter, rye flour, feeding jar, and revival guide.",
    "price": 29.99,
    "rating": 4.6,
    "reviews": 201,
    "difficulty": "Beginner",
    "category": "Sourdough",
    "tags": ["backup", "travel-friendly"],
    "inStock": true,
    "image": "/images/kits/starter-revival.jpg"
  },
  {
    "id": 32,
    "title": "Fermentation Crock Collection",
    "description": "1L, 3L, 5L crocks with weights and lids.",
    "price": 199.99,
    "rating": 5.0,
    "reviews": 54,
    "difficulty": "Intermediate",
    "category": "Vegetable Fermentation",
    "tags": ["set", "heirloom"],
    "inStock": true,
    "image": "/images/kits/crock-collection.jpg"
  },
  {
    "id": 33,
    "title": "Kombucha Gift Box",
    "description": "Mini SCOBY, jar, tea, sugar, and holiday card.",
    "price": 39.99,
    "rating": 4.9,
    "reviews": 176,
    "difficulty": "Beginner",
    "category": "Kombucha",
    "tags": ["gift", "stocking stuffer"],
    "inStock": true,
    "image": "/images/kits/kombucha-gift.jpg"
  },
  {
    "id": 34,
    "title": "Sourdough Science Kit",
    "description": "pH meter, hydrometer, flour samples, and baking log.",
    "price": 84.99,
    "rating": 4.8,
    "reviews": 73,
    "difficulty": "Advanced",
    "category": "Sourdough",
    "tags": ["nerd", "data-driven"],
    "inStock": true,
    "image": "/images/kits/sourdough-science.jpg"
  },
  {
    "id": 35,
    "title": "Fermented Soda Starter Set",
    "description": "Ginger bug, fruit syrups, bottles, and soda recipes.",
    "price": 46.99,
    "rating": 4.7,
    "reviews": 134,
    "difficulty": "Beginner",
    "category": "Beverages",
    "tags": ["kid-friendly", "probiotic soda"],
    "inStock": true,
    "image": "/images/kits/soda-set.jpg"
  },
  {
    "id": 36,
    "title": "Kombucha Brewery Upgrade",
    "description": "Heating mat, insulation jacket, auto-siphon, and brew log.",
    "price": 99.99,
    "rating": 4.9,
    "reviews": 88,
    "difficulty": "Intermediate",
    "category": "Kombucha",
    "tags": ["year-round", "pro"],
    "inStock": true,
    "image": "/images/kits/brewery-upgrade.jpg"
  },
  {
    "id": 37,
    "title": "Sourdough Bread Box Subscription (1st Month)",
    "description": "Fresh starter, flour, recipe, and tools — monthly delivery.",
    "price": 49.99,
    "rating": 4.8,
    "reviews": 203,
    "difficulty": "Beginner",
    "category": "Sourdough",
    "tags": ["subscription", "fresh"],
    "inStock": true,
    "image": "/images/kits/bread-box.jpg"
  },
  {
    "id": 38,
    "title": "Fermented Tea Explorer",
    "description": "Kombucha, jun, and kvass cultures + tea blends.",
    "price": 74.99,
    "rating": 4.7,
    "reviews": 99,
    "difficulty": "Intermediate",
    "category": "Beverages",
    "tags": ["tea lover", "variety"],
    "inStock": true,
    "image": "/images/kits/tea-explorer.jpg"
  },
  {
    "id": 39,
    "title": "Sourdough Discard Recipe Kit",
    "description": "Crackers, pancakes, pizza dough mix, and discard guide.",
    "price": 32.99,
    "rating": 4.8,
    "reviews": 167,
    "difficulty": "Beginner",
    "category": "Sourdough",
    "tags": ["zero waste", "snacks"],
    "inStock": true,
    "image": "/images/kits/discard-kit.jpg"
  },
  {
    "id": 40,
    "title": "Ultimate Fermentation Master Set",
    "description": "All-in-one: crocks, jars, cultures, tools, and 200-page guidebook.",
    "price": 299.99,
    "rating": 5.0,
    "reviews": 42,
    "difficulty": "Advanced",
    "category": "Multi-Use",
    "tags": ["complete", "lifetime", "limited"],
    "inStock": false,
    "image": "/images/kits/master-set.jpg"
  }
]
}